name: KiTeecoin-core # you probably want to 'snapcraft register <name>'
version: '1.14.5'
summary: Reference client of KiTeecoin, a peer-to-peer digital currency like Bitcoin.
description: |
  KiTeecoin is a cryptocurrency like Bitcoin, although it does not use SHA256 as its proof of work (POW). Taking development cues from Tenebrix and Litecoin, KiTeecoin currently employs a simplified variant of scrypt. MIT licenced.

base: core18
grade: stable
confinement: strict
architectures:
  - build-on: [amd64, i386, arm64]

apps:
  d:
    command: KiTeecoind
    plugs: [home, removable-media, network, network-bind]
    environment:
    # Override HOME so the datadir is located at ~/snap/KiTeecoin-core/common/.KiTeecoin/ instead of ~/snap/KiTeecoin-core/current/.KiTeecoin/, and each new version of the snap won't have a different data directory: https://docs.snapcraft.io/environment-variables/7983
      HOME: $SNAP_USER_COMMON
  qt:
    command: qt4-launch KiTeecoin-qt
    plugs: [home, removable-media, network, network-bind, desktop, x11, unity7]
    environment:
      HOME: $SNAP_USER_COMMON
      DISABLE_WAYLAND: 1
  cli:
    command: KiTeecoin-cli
    plugs: [home, removable-media, network]
    environment:
      HOME: $SNAP_USER_COMMON

parts:
  KiTeecoin-core:
    plugin: nil
    override-build: |
      echo "Downloading files..."
      wget https://github.com/KiTeecoin/KiTeecoin/releases/download/v${SNAPCRAFT_PROJECT_VERSION}/KiTeecoin-${SNAPCRAFT_PROJECT_VERSION}-${SNAPCRAFT_ARCH_TRIPLET}.tar.gz
      wget https://github.com/KiTeecoin/gitian.sigs/archive/refs/heads/master.zip
      unzip master.zip
      echo "Verifying secure hash matches signed values..."
      checksum=$(sha256sum KiTeecoin-${SNAPCRAFT_PROJECT_VERSION}-${SNAPCRAFT_ARCH_TRIPLET}.tar.gz)
      if ! (grep -r $checksum * | grep KiTeecoin-${SNAPCRAFT_PROJECT_VERSION}-${SNAPCRAFT_ARCH_TRIPLET}.tar.gz); then
        echo "Secure hash not verified."
        return
      else
        echo "Secure hash verified."
      fi
      tar -xvf KiTeecoin-${SNAPCRAFT_PROJECT_VERSION}-${SNAPCRAFT_ARCH_TRIPLET}.tar.gz
      echo "Running tests..."
      if ! (KiTeecoin-${SNAPCRAFT_PROJECT_VERSION}/bin/test_KiTeecoin); then
        echo "KiTeecoin tests failed."
        return
      else
        echo "KiTeecoin tests passed."
      fi
      echo "Installing KiTeecoin..."
      install -m 0755 -D -t $SNAPCRAFT_PART_INSTALL/bin KiTeecoin-${SNAPCRAFT_PROJECT_VERSION}/bin/KiTeecoin
      install -m 0755 -D -t $SNAPCRAFT_PART_INSTALL/bin KiTeecoin-${SNAPCRAFT_PROJECT_VERSION}/bin/KiTeecoin-qt
      install -m 0755 -D -t $SNAPCRAFT_PART_INSTALL/bin KiTeecoin-${SNAPCRAFT_PROJECT_VERSION}/bin/KiTeecoin-cli
      wget https://raw.githubusercontent.com/KiTeecoin/KiTeecoin/master/share/pixmaps/KiTeecoin128.png
      install -m 0644 -D -t $SNAPCRAFT_PART_INSTALL/share/pixmaps KiTeecoin128.png
    build-packages:
      - unzip
      - wget
    stage-packages:
      - libfreetype6
      - libpng16-16
      - libx11-xcb1
      - libx11-6
      - libfontconfig
  qt4conf:
    build-packages:
      - dpkg-dev
    plugin: make
    source: https://github.com/kyrofa/qt4conf.git
